### ISSUE TITLE
Holder snapshot returns empty

### ISSUE THREAD

**Issue by studionx** [penta-fun/sol-nft-tools#7]
As title said, Get Holders returns an empty {}

**Comment by 21e8** [comment]
@studionx sorry for the late response, we had some issues I am currently resolving

**Comment by studionx** [comment]
Hey Alice,
Thank you for getting back! No worries there. I managed to learn from the
sol cookbooks and manage to come up with my own holder snapshot tool.
Thank you for making your tool free to use :)

Cheers!

**Comment by 21e8** [comment]
Awesome!
